config/routes.rb
Rails.application.routes.draw do

  get "/photos/get_data", to: "photos#get_data", defaults: { format: 'json' }

  resources :photos, except: [:edit, :update]
  resources :locations, except: [:new, :create]

  root to: "locations#index"

end

app/models/flight_summary.rb
class FlightSummary
  include Mongoid::Document

  embedded_in :photo, inverse_of: :flight_summary

  field :operator_name, type: String
  field :aircraft_type, type: String
  field :tail_number, type: String
  field :payload, type: String
  field :notes, type: String
end

app/models/geo_location.rb
class GeoLocation
  include Mongoid::Document

  field :loc, type: Hash
  field :lat, type: Float
  field :lng, type: Float

  before_save :set_geolocation

  def set_geolocation
    self.loc = { type: "Point", coordinates: [self.lng, self.lat] }
  end

  def latlng
    coords = self.loc[:coordinates]
    Geokit::LatLng.new(coords[1], coords[0])
  end

  def distance_to(poi)
    self.latlng.distance_to(poi.latlng)
  end
end

app/models/location.rb
class Location < GeoLocation

  field :poi, type: Integer

  has_many :photos, inverse_of: :location

  def name
    "POI #{self.poi}"
  end

end

app/models/photo.rb
class Photo < GeoLocation
  include Mongoid::Paperclip

  belongs_to :location, inverse_of: :photos, optional: true
  embeds_one :flight_summary, inverse_of: :photo

  accepts_nested_attributes_for :flight_summary

  field :metadata, type: Hash
  field :notes, type: String

  has_mongoid_attached_file :attachment, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\z/

  before_post_process :extract_metadata
  before_save :set_latlng, :set_geolocation, :assign_location

  def extract_metadata
    tempfile = attachment.queued_for_write[:original].path
    data = Exif::Data.new(tempfile)
    false if data[:gps][:gps_latitude].blank? || data[:gps][:gps_longitude].blank?
    self.metadata = data.to_h
  end

  def set_latlng
    gps = self.metadata[:gps]
    self.lat = gps[:gps_latitude_ref] == 'N' ? gps[:gps_latitude] : -gps[:gps_latitude]
    self.lng = gps[:gps_longitude_ref] == 'E' ? gps[:gps_longitude] : -gps[:gps_longitude]
  end

  def assign_location
    location = nil
    #NOTE: This is a time consuming operation as the no of location's increase we should either improve the query 
    #using mongodb geo capabilities or move it to bacground job 
    Location.all.each do |l|
      if self.distance_to(l) < 10
        location = l
        break
      end
    end
    if location.blank?
      poi = Location.max(:poi) || 0
      location = Location.create(poi: poi + 1, lat: self.lat, lng: self.lng)
    end
    self.location = location
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def edit
  end

  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.fetch(:location, {}).permit(:name, photos_attributes: [:attachment])
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
    @photo.flight_summary.build
  end

  def edit
  end

  def create
    @flight_summary = FlightSummary.new(flight_params)
    respond_to do |format|
      if @flight_summary.save
        format.html { redirect_to locations_url, notice: 'Photos successfully uploaded.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @flight_summary.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, photo: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def flight_params
      params.fetch(:photo, {}).permit(:operator_name, :aircraft_type, :tail_number, :payload, :notes, photos_attributes: [:attachment])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_footer.html.erb
<hr/>
<footer class="text-center">
  <p>©<%= Date.today.year %> AviSight</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">AviSight</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="<%=locations_path%>">Dashboard <span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%=new_photo_path%>">Upload Photos<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-right mr-1">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-2x"></i>
        </a>
        <ul class="dropdown dropdown-menu dropdown-user">
            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="text" placeholder="Search locations">
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AviSight</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render partial: "layouts/navbar"%>
      <div class="container">
        <div class="row">
          <div class="col-offset-1 col-12 col-md-9 " id="main">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: "layouts/footer"%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true, html: { multipart: true }) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>
      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= file_field_tag 'location_photos_attributes_attachment', multiple: true, name: "location[photos_attributes][][attachment]", class: 'form-control-file btn btn-outline-primary' %>
  </div>
  <div class="form-group">
    <%= form.submit "Create" , class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<h4>Locations</h4>
<div id="map"></div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th># of Photos</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td class="col-6"><%= location.name %></td>
        <td class="col-6"><%= location.photos.count %></td>
        <td class="col-2"><%= link_to '<i class="fa fa-map-marker"></i>'.html_safe, location %></td>
        <td class="col-2"><%= link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_location_path(location)  %></td>
        <td class="col-2"><%= link_to '<i class="fa fa-trash-o fa-lg"></i>'.html_safe, location, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if @locations.present? %>
<script>
  function initMap() {
    var uluru = {lat: <%= @locations[0].lat %>, lng: <%= @locations[0].lng %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 16,
      mapTypeId: google.maps.MapTypeId.HYBRID,
      center: uluru
    });
    <% @locations.each_with_index do |location, i| 
      content = '<ul class="photo_list">'
      for photo in location.photos do
        content += "<li><img src=\"#{photo.attachment.url(:medium)}\"></li>"
      end
      content += '</ul>'
    %>
    infowindow_<%= i %> = new google.maps.InfoWindow({
      content: '<%= raw content %>'
    });
    marker_<%= i %> = new google.maps.Marker({
      position: {lat: <%= location.lat %>, lng: <%= location.lng %>},
      map: map,
      title: "<%= location.name %>",
      animation: google.maps.Animation.DROP,
    });
    marker_<%= i %>.addListener('click', function() {
      infowindow_<%= i %>.open(map, marker_<%= i %>);
    });
    <% end %>
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBn7yG3_RN21nDgK5gWa-v4Doar92gO7wo&callback=initMap" type="text/javascript"></script>
<% end %>

app/views/locations/new.html.erb
<h4>New Location</h4>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Name: <%= @location.name %></h3>
<p>Location: <%= @location.lat %>, <%= @location.lng %></h3></p>
<div class="row">
  <ul class="photo_list">
  <%= render @location.photos %>
  </ul>
</div>
<h3>Map</h3>
<div id="map"></div>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

<script>
  function initMap() {
    var uluru = {lat: <%= @location.lat %>, lng: <%= @location.lng %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 18,
      mapTypeId: google.maps.MapTypeId.HYBRID,
      center: uluru
    });
    <% @location.photos.each_with_index do |photo, i| %>
    infowindow_<%= i %> = new google.maps.InfoWindow({
      content: '<img src="<%= photo.attachment.url(:medium) %>">'
    });
    marker_<%= i %> = new google.maps.Marker({
      position: {lat: <%= photo.lat %>, lng: <%= photo.lng %>},
      map: map,
      title: "<%= photo.attachment.original_filename %>",
      animation: google.maps.Animation.DROP,
    });
    marker_<%= i %>.addListener('click', function() {
      infowindow_<%= i %>.open(map, marker_<%= i %>);
    });
    <% end %>
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBn7yG3_RN21nDgK5gWa-v4Doar92gO7wo&callback=initMap" type="text/javascript"></script>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true, html: { multipart: true }) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited the images from uploading:</h2>
      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.fields_for :flight_summary do |fs_form| %>
    <div class="form-group">
      <%= fs_form.label :operator_name %>
      <%= fs_form.text_field :operator_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= fs_form.label :aircraft_type %>
      <%= fs_form.text_field :aircraft_type, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= fs_form.label :tail_number %>
      <%= fs_form.text_field :tail_number, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= fs_form.label :payload %>
      <%= fs_form.text_field :payload, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= fs_form.label :notes %>
      <%= fs_form.text_area :notes, cols: 40, rows: 5, class: "form-control" %>
    </div>
  <% end %>
  <div class="form-group">
    <%= file_field_tag 'photo_attributes_attachment', multiple: true, name: "photo[][attachment]", class: 'form-control-file btn btn-outline-primary' %>
  </div>
  <div class="form-group">
    <%= form.submit "Upload" , class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<li><%= image_tag photo.attachment.url(:thumb) %></li>

app/views/photos/edit.html.erb
<h4>Editing Photo</h4>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Picture Database</h4>

<table class="table" id="table">
  <thead>
    <tr>
      <th>Filename</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.attachment.original_filename %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div id="myGrid" style="width:600px; height:500px;"></div>
<br>
<%= link_to 'Upload Photos', new_photo_path %>

app/views/photos/new.html.erb
<h4>Upload Photos</h4>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', locations_path, class: 'btn btn-outline-secondary' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>